use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A Proprietary Compliance Protocol (PCP) generated by REGENT.
/// This defines the machine-readable standard that risk contracts must meet
/// to be executed over the Sovereign Bridge.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ComplianceProtocol {
    pub pcp_id: String, // e.g., "PCP-EU-SLD-001"
    pub jurisdiction: String,
    pub instrument_type: String,
    pub requirements: Vec<ComplianceRequirement>,
    pub penalty_modifier: f64, // e.g., 0.15 for a 15% withhold penalty
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ComplianceRequirement {
    Disclosure(String),
    DataStandard(String),
    ExternalAuditHash(String),
}

/// The Normative Enforcer gates access to the Actuarial Engine.
/// Contracts must pass this gateway to be priced and settled.
pub struct NormativeEnforcer {
    active_protocols: HashMap<String, ComplianceProtocol>,
}

impl Default for NormativeEnforcer {
    fn default() -> Self {
        Self::new()
    }
}

impl NormativeEnforcer {
    pub fn new() -> Self {
        let mut enforcer = Self {
            active_protocols: HashMap::new(),
        };
        // Load Genesis PCP: The EU Sustainability-Linked Derivatives standard
        enforcer.load_genesis_pcp();
        enforcer
    }

    fn load_genesis_pcp(&mut self) {
        let genesis_pcp = ComplianceProtocol {
            pcp_id: "PCP-EU-SLD-001".to_string(),
            jurisdiction: "EU".to_string(),
            instrument_type: "synthetic_weather_derivative".to_string(),
            requirements: vec![
                ComplianceRequirement::Disclosure("climate_model_attribution".to_string()),
                ComplianceRequirement::DataStandard("ISO-20022-ESG".to_string()),
            ],
            penalty_modifier: 0.15,
        };
        self.active_protocols.insert(genesis_pcp.pcp_id.clone(), genesis_pcp);
    }

    /// Evaluates a raw contract definition against the active Proprietary Compliance Protocols.
    pub fn enforce(&self, pcp_id: &str, contract_metadata: &HashMap<String, String>) -> Result<(), String> {
        let pcp = self.active_protocols.get(pcp_id)
            .ok_or_else(|| format!("Unknown PCP: {}", pcp_id))?;

        println!("   [REGENT] ⚖️ Enforcing compliance protocol: {}", pcp.pcp_id);

        for req in &pcp.requirements {
            match req {
                ComplianceRequirement::Disclosure(key) => {
                    if !contract_metadata.contains_key(key) {
                        return Err(format!("Missing required disclosure: {}", key));
                    }
                },
                ComplianceRequirement::DataStandard(std) => {
                    if contract_metadata.get("data_standard") != Some(std) {
                        return Err(format!("Data standard must match: {}", std));
                    }
                },
                _ => {}
            }
        }

        println!("   [REGENT] ✅ Contract validated against {}", pcp.pcp_id);
        Ok(())
    }
}
